pull_request_rules:
  - name: VM5_POST_CHECK_EXTERNAL_MERGE_AFTER_MP_260918
    conditions:
      - title = VM5 POSTCHECK EXTERNAL 260918
      - check-success = Mergify Merge Protections
    actions:
      merge:
        method: merge
merge_protections:
  # Migrated from post_check rule 'VM5_POST_CHECK_EXTERNAL_FLAT_OR_260918'. Dropped options with no equivalent: title, summary
  - name: VM5_POST_CHECK_EXTERNAL_FLAT_OR_260918
    if:
      - title = VM5 POSTCHECK EXTERNAL 260918
    success_conditions:
      - or:
          - title = VM5 POSTCHECK EXTERNAL 260918
          - check-success = vm5-never-pass-postcheck-external-260918
          - label = vm5-never-neutral-c-postcheck-260918
          - label = vm5-never-neutral-d-postcheck-260918
